image: alpine:latest

include:
  - project: 'cloudnua-public/gitops/infra/templates'
    ref: main
    file:
      - '/terraform.gitlab-ci.yml'

# Using protected pipeline variable for initial deployment
variables:
  GCP_CREDENTIALS: $GCP_CRED
  GCP_PROJECT_ID: $GCP_PROJ_ID
  GCP_REGION: $GCP_REG
  GITLAB_TOKEN: $GITLAB_TOKEN

# Using protected pipeline variable for initial deployment
before_script:
  - echo "Initialise GCP GKE Stack...START!"
  - echo $GCP_CREDENTIALS | base64 -d > gcp-key.json
  - export TF_CREDS=gcp-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=${TF_CREDS}
after_script:
  - rm gcp-key.json
  - echo ""Initialise GCP GKE Stack...DONE!""